frmLen = 100;
sigma2 = 1;
intrlvr = randperm(frmLen);  % the interleaver indices
hTEnc = comm.TurboEncoder('InterleaverIndices', intrlvr);
hTDec = comm.TurboDecoder('InterleaverIndices', intrlvr);
data = randi([0 1],frmLen,1);            % Generate random binary data     
encodedData = step(hTEnc,data);  % Turbo encode the data   
modSignal = 1 - 2*encodedData;    % Modulate the encoded data 
noise_v = randn(length(modSignal),1);
receivedSignal = modSignal + sqrt(sigma2) * noise_v;     
demodSignal =  2*receivedSignal/sigma2;    % Demodulating 
receivedBits = step(hTDec,-demodSignal);   % Turbo decoding
errorNum = sum( abs(data - receivedBits) );  % the error statistics